### ISSUE TITLE
I put in my video through the editor but it doesn't seem to have a download link or a way I can download it.

### ISSUE THREAD

**Issue by some-guy-0** [supermosh/supermosh.github.io#6] opened 2023-11-13 16:09 UTC

**Comment by ninofiliu** [comment] 2023-11-14 09:26
Right click on the video and save it

**Comment by some-guy-0** [comment] 2023-11-15 17:59
> Right click on the video and save it

That's what I done, but it only saved the part that was edited.

**Comment by ninofiliu** [comment] 2023-11-15 18:23
Isn't it the expected behavior? Can you please

- [ ] upload your vids here
- [ ] describe your segments (either via screenshots or via text)
- [ ] tell me what OS you are using
- [ ] tell me what browser and browser version you are using
- [ ] describe precisely the expected behavior and how it differs from what you observe

**Comment by ninofiliu** [comment] 2023-11-15 18:56
you're supposed to right click on the video and save it. there is no download button. here's how to do this

[capture(1).webm](https://github.com/supermosh/supermosh.github.io/assets/29477588/3a5f4041-a9bb-429c-85c2-cf0ec17803b2)

**Comment by some-guy-0** [comment] 2023-11-15 19:17
> you're supposed to right click on the video and save it. there is no download button. here's how to do this
> 
>  capture.1.webm

Well then my whole video will just be a blurry mess, since the rest of the video is cut out and the only part of the video is the data mosh.

**Comment by ninofiliu** [comment] 2023-11-15 20:47
I can't reproduce the issue. I can render copy, glide, and movement segments with no issue. Included a generation I did just now, as you can see there is more than just the data mosh:

[DzVeqKNj.webm](https://github.com/supermosh/supermosh.github.io/assets/29477588/ede8301a-a467-4a36-9c35-c6ebe99cac8d)

**Comment by some-guy-0** [comment] 2023-11-16 15:50
Now my output won't stop coming out as black.

**Comment by ninofiliu** [comment] 2023-11-16 16:08
I'm going to close the issue until you provide all informations necessary for me to reproduce your issue

**Closed by ninofiliu** 2023-11-16 16:08 UTC

**Comment by some-guy-0** [comment] 2023-11-16 18:29
Just forget it, I'll use a different website or something.
